on:
    push:
        branches:
            - main
permissions:
  contents: write

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: A job to automate contrib in readme
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@v2.3.6
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # auto_screenshot_from_fdroid:
    #   runs-on: ubuntu-latest
    #   name: Automatically Get Screenshots From F-Droid

    #   steps:
    #     - name: Checkout Repository
    #       uses: actions/checkout@v2

    #     - name: Set up Python
    #       uses: actions/setup-python@v2
    #       with:
    #             python-version: 3.x

    #     - name: Install Dependencies
    #       run: pip install -r Scripts/requirements.txt  # If you have any dependencies

    #     - name: Run the Script
    #       run: python Scripts/auto_screenshot_from_fdroid.py

    #     - name: Commit and Push Changes
    #       run: |
    #         git config --local user.email "action@github.com"
    #         git config --local user.name "GitHub Action"
    #         git add .
    #         git commit -m "دریافت خودکار نماگرفت ها از اف دروید"
    #         git push
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Configure Git Credentials
          run: |
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        - uses: actions/setup-python@v5
          with:
            python-version: 3.x
        - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

        - uses: actions/cache@v4
          with:
            key: mkdocs-material-${{ env.cache_id }}
            path: .cache
            restore-keys: |
              mkdocs-material-
        - run: pip install mkdocs-material

        - run: mkdocs gh-deploy --force
